// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf1ZbCl7hzOPOAqrmfrNxfmiFCtxplzkE',
    appId: '1:993818877548:web:e946700f298c9d90c48249',
    messagingSenderId: '993818877548',
    projectId: 'smilequiz',
    authDomain: 'smilequiz.firebaseapp.com',
    storageBucket: 'smilequiz.appspot.com',
    measurementId: 'G-0YLZTT5CVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA127jVDYgbIqwPDxmSxB4O9d-8T4XNXKc',
    appId: '1:993818877548:android:9973eb58e9ff494cc48249',
    messagingSenderId: '993818877548',
    projectId: 'smilequiz',
    storageBucket: 'smilequiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3RKdrfD48mVk_YFCz8Dy1k-hiHBPZCtc',
    appId: '1:993818877548:ios:ea019c709cc732e8c48249',
    messagingSenderId: '993818877548',
    projectId: 'smilequiz',
    storageBucket: 'smilequiz.appspot.com',
    androidClientId: '993818877548-pjgmatau3bpu55kdo8kp19865j1u4lo4.apps.googleusercontent.com',
    iosClientId: '993818877548-9ujfm4u794ntlfkp5gsb7neeeevbo6nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smileQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3RKdrfD48mVk_YFCz8Dy1k-hiHBPZCtc',
    appId: '1:993818877548:ios:ea019c709cc732e8c48249',
    messagingSenderId: '993818877548',
    projectId: 'smilequiz',
    storageBucket: 'smilequiz.appspot.com',
    androidClientId: '993818877548-pjgmatau3bpu55kdo8kp19865j1u4lo4.apps.googleusercontent.com',
    iosClientId: '993818877548-9ujfm4u794ntlfkp5gsb7neeeevbo6nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smileQuiz',
  );
}
